language: objective-c
osx_image: xcode10.2
env:
  - DESTINATION="OS=12.2,name=iPhone X" SCHEME="Example" SDK=iphonesimulator12.2

before_install:
- pod install --project-directory=TokenRow/Example
- gem install xcpretty --quiet

script:
- xcodebuild clean build -workspace TokenRow/Example/Example.xcworkspace -scheme "$SCHEME" -sdk "$SDK"
- xcodebuild test -workspace TokenRow/Example/Example.xcworkspace -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" | xcpretty -c
