source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

def pods
	pod 'Alamofire', '~> 3.5'
    pod 'AlamofireImage'
    pod 'CLTokenInputView', '~> 2.0'
	pod 'TokenRow', :path => '../../'
end

target 'Example' do
    pods
end

target 'TokenRowTests' do
    pods
end
