source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'Example' do
	pod 'Alamofire', '~> 3.5'
    pod 'AlamofireImage'
    pod 'CLTokenInputView'
	pod 'TokenRow', :path => '../../'
end

